baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Marek Jakub'

paginate = 4

[params]
  description = "Marek Jakub blogging"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
