baseURL = 'https://marek-jakub.github.io'
languageCode = 'en-us'
title = 'Marek Jakub'

paginate = 5

[params]
  description = "Marek Jakub blogging"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
