baseURL = 'https://marek-jakub.github.io'
languageCode = 'en-us'
title = 'Marek Jakub'

[pagination]
  disableAliases = false
  pagerSize = 5
  path = 'page'

[params]
  description = "Marek Jakub blogging"
  dateFormat = "Jan 2, 2006"
  showReadingTime = false

[taxonomies]
  category = "categories"
  author = "authors"
